### PR TITLE
[#13] implement html filter

### PR DESCRIPTION
**Pull request by pbatroff**
I copied the class and functionality from flexmailer and added it to _civicrm_api3_job_mosaico_msg_filter. I tested this on CiviCRM 5.13.4 with mosaico 2.2, but I don't se it not working in newer versions of Civi/Mosaico. 

The code is straight forward and the same as flexmailer.

@MikeyMJCO @artfulrobot Could one of you review this and then merge the PR please?

### CODE REVIEW

**Comment by homotechsual** [comment]
I'd like to reuse the FlexMailer class if we can instead of copying it. We've got a hard dependency on FlexMailer anyway via the Mosaico dependency on FM - so we can expect it to always be there.

**Comment by pbatroff** [comment]
> I'd like to reuse the FlexMailer class if we can instead of copying it. We've got a hard dependency on FlexMailer anyway via the Mosaico dependency on FM - so we can expect it to always be there.

Ok, I agree! But I also mispoke a bit. The class is from mosaico, and extends flexmailer: 

`class CRM_Mosaico_UrlFilter extends \Civi\FlexMailer\Listener\BaseListener 
`

Let me see if I can reuse it instead!

**Comment by pbatroff** [comment]
works well, tested in the same environment.

**Comment by homotechsual** [comment]
Currently testing on 5.19.1 with extension vMaster and Mosaico v2.3

**Comment by homotechsual** [comment]
Tested OK on latest Mosaico/Civi/MsgTpl

Merging.

**Pull request merged**
