### PR TITLE
implement deleting of message template when corresponding mosaico template is deleted 

### LINKED ISSUE #18: Deleting Mosaico template should also delete corresponding message template
## Problem
* After deletion of Mosaico template corresponding message templates are not deleted. These message templates are marked as 'is_reserved=1' hence, it can't be deleted using Message template UI. This creates unnecessary confusion as CiviCRM still shows the message templates that have been deleted in Mosaico.

## Solution
* When Mosaico template is deleted, it should also delete corresponding template.

Let me know if I am missing something or if this is a bad idea.

### PR DESCRIPTION
**Pull request by kurund**
Fix for #18

### CODE REVIEW

**Review by homotechsual — APPROVED** [review]
Looks good to me.

**Comment by kurund** [comment]
@artfulrobot 

Apologies for the delayed response.

I am using civicrm_pre_hook and then API calls to delete the corresponding message template. In order to test this functionality I will have to replicate the same. API's are already separately tested hence, wondering if we still need additional tests.

**Comment by homotechsual** [comment]
> @artfulrobot
> 
> Apologies for the delayed response.
> 
> I am using civicrm_pre_hook and then API calls to delete the corresponding message template. In order to test this functionality I will have to replicate the same. API's are already separately tested hence, wondering if we still need additional tests.

Currently we only test the template sync. It would be good to add a test against template deletion.

**Comment by kurund** [comment]
@MikeyMJCO 

We don't have an API for deletion. I am using `civicrm_api3('MosaicoTemplate', 'get')` which is part of Mosaico extension and `civicrm_api3('MessageTemplate', 'delete')` which is CiviCRM. Both of them already have tests and writing unit tests for the same might be redundant.

**Comment by homotechsual** [comment]
> @MikeyMJCO
> 
> We don't have an API for deletion. I am using `civicrm_api3('MosaicoTemplate', 'get')` which is part of Mosaico extension and `civicrm_api3('MessageTemplate', 'delete')` which is CiviCRM. Both of them already have tests and writing unit tests for the same might be redundant.

I think what Rich is suggesting is a test that does the following:

1. Creates a Mosaico Template.
2. Syncs it to generate a Message Template.
3. Deletes the Mosaico Template.
4. Checks that the Message Template has also been deleted.

If that's correct @artfulrobot I can write the test.

**Comment by kurund** [comment]
@artfulrobot @MikeyMJCO 

Completely agree with the test driven approach and I am kind of in a same boat :)

> 1. Creates a Mosaico Template.
> 2. Syncs it to generate a Message Template.
> 3. Deletes the Mosaico Template.
> 4. Checks that the Message Template has also been deleted.

This make sense. Let me give it a try.

**Comment by kurund** [comment]
```

  /**
   * Test deletion of message template corresponding to masaico template
   */
  public function testDelete() {
    $this->assertEquals('MosaicoTemplate', CRM_Core_DAO_AllCoreTables::getBriefName('CRM_Mosaico_DAO_MosaicoTemplate'));

    // Create the first template and run the sync.
    $first = $this->createMosaicoTemplate(array('title' => 'First example'));
    civicrm_api3('Job', 'mosaico_msg_sync', ['id' => $first['id']]);

    // Delete mosaico template
    civicrm_api3('MosaicoTemplate', 'delete', array('id' => $first['id']));;

    // we need to emulate pre hook - which means run message template delete

    // make sure message template is deleted
    $result = civicrm_api3('MessageTemplate', 'getsingle', ['id' => $first['msg_tpl_id']]);
    $this->assertEquals($result['count'], 0);
  }

```

We could potentially do something like above.  What do you suggest to emulate pre hook behavior?

**Comment by homotechsual** [comment]
Sorry Kurund, brain running slow, what do you mean by "emulate pre-hook behaviour" here?

**Comment by kurund** [comment]
> // Delete mosaico template
>     civicrm_api3('MosaicoTemplate', 'delete', array('id' => $first['id']));

This will only delete the Mosaico template and I think will invoke `pre_hook` ( and the code in that) only when we delete it via UI.  or may be I am missing something here?

**Comment by kurund** [comment]
@artfulrobot Nope, i am not sure. However, I did a quick test using api explorer and it does trigger the pre_hook. I am having issues with running tests. I have committed the test. It would be great if you or @MikeyMJCO give it a try.

**Comment by homotechsual** [comment]
> @artfulrobot Nope, i am not sure. However, I did a quick test using api explorer and it does trigger the pre_hook. I am having issues with running tests. I have committed the test. It would be great if you or @MikeyMJCO give it a try.

Testing now.

**Comment by homotechsual** [comment]
@artfulrobot when we move this to GitLab (if?) #20 we can run the test suite against any PRs automatically - which will be nice for these scenarios :-D

**Comment by homotechsual** [comment]
Pushed a fix - tests passing. Looks like it's working as intended now :-)

Given the test is passing and the functionality works - I'm going to merge this. Thanks @Kurund <3

**Comment by homotechsual** [comment]
**Test results:**

PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

Parsing schema description /opt/buildkit/build/dmaster/web/sites/all/modules/civicrm/xml/schema/Schema.xml
Extracting database information
Extracting table information
........                                                            8 / 8 (100%)

Time: 11.14 seconds, Memory: 36.00MB

OK (8 tests, 35 assertions)

**Comment by homotechsual** [comment]
and PHPUnit6 for good measure:

PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

Parsing schema description /opt/buildkit/build/dmaster/web/sites/all/modules/civicrm/xml/schema/Schema.xml
Extracting database information
Extracting table information
........                                                            8 / 8 (100%)

Time: 2.16 seconds, Memory: 34.00MB

OK (8 tests, 35 assertions)

**Pull request merged**
